### ISSUE TITLE
Create Database Error

### ISSUE THREAD

**Issue by onimsha** [osiell/oerplib#14]
Currently the db.create() has the following error while running against Odoo8:

Python>oerp = oerplib.OERP(server='localhost')
Python>oerp.db.create('super_admin_pass', 'my_db', False, 'fr_FR', 'admin_passwd')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/oerplib/service/db.py", line 276, in rpc_method
oerplib.error.RPCError: (1, 'Traceback (most recent call last):\n  File "/opt/python27/lib/python2.7/site-packages/odoo-8.0_edbd0df-py2.7.egg/openerp/service/wsgi_server.py", line 75, in xmlrpc_return\n    result = openerp.http.dispatch_rpc(service, method, params)\n  File "/opt/python27/lib/python2.7/site-packages/odoo-8.0_edbd0df-py2.7.egg/openerp/http.py", line 108, in dispatch_rpc\n    result = dispatch(method, params)\n  File "/opt/python27/lib/python2.7/site-packages/odoo-8.0_edbd0df-py2.7.egg/openerp/service/db.py", line 69, in dispatch\n    fn = globals()[\'exp_\' + method]\nKeyError: u\'exp_create\'\n')

Maybe there is some incompatible with the current xmlrpc of Odoo8?

**Comment by sebalix** [comment]
Hi,

What version of OERPLib are you using?

But it could be an Odoo v8 problem, as the `db.create()` method seems deprecated in this version.
Can you try the `db.create_database()` one?

``` python
oerp.db.create_database('super_admin_pass', 'my_db', False, 'fr_FR', 'admin_passwd')
```

http://pythonhosted.org//OERPLib/ref_db.html#DB.create_database

**Comment by onimsha** [comment]
My OERPLib version is 0.8.4. the db.create_database() works fine on my server. I think you should update the document for Odoo8 database create creation case(https://pythonhosted.org/OERPLib/tutorials.html#manage-databases) .

Thanks very much

**Comment by sebalix** [comment]
Thanks for the feedback!
