### ISSUE TITLE
Compatibility with odoo9

### ISSUE THREAD

**Issue by llonchj** [osiell/oerplib#18]
I am getting errors using oerplib with odoo9c. What are the future plans for oerplib in order to support odoo9?

**Comment by sebalix** [comment]
Hi,

The plan is to migrate to OdooRPC for Odoo >= 8:
- Doc : http://pythonhosted.org/OdooRPC/
- PyPI : https://pypi.python.org/pypi/OdooRPC
- Github : https://github.com/osiell/odoorpc/

A brief explanation why OdooRPC: http://pythonhosted.org/OdooRPC/faq.html#why-odoorpc-and-why-migrate-from-oerplib-to-odoorpc
Of course, any contribution to make OERPLib compatible with Odoo 9 is welcome! But here at OSIELL we only use OERPLib for projects running on OpenERP 5.0 to 7.0. Starting from Odoo 8.0 we are using exclusively OdooRPC.

Regards,

**Comment by llonchj** [comment]
Thanks @sebalix
