### ISSUE TITLE
Port to python3

### ISSUE THREAD

**Issue by sedrubal** [osiell/oerplib#21]
Currently oerplib only supports python2 but we need python3 support.

**Comment by sebalix** [comment]
OERPLib is no longer maintained, please take a look to [OdooRPC](http://pythonhosted.org/OdooRPC/) ([GitHub](https://github.com/osiell/odoorpc)) which supports Python 2.7 and all Python 3.X releases.

**Comment by sebalix** [comment]
Closing.
